spring:
  datasource:
    master:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST_MASTER}:3306/${DB_NAME}
    slave:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST_SLAVE}:3306/${DB_NAME}
    slave2:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST_SLAVE2}:3306/${DB_NAME}
  jpa:
#        로컬
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

cloud:
  aws:
    baseUrl : ${AWS_URL}
    s3:
      bucket: ${AWS_BUCKET}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}