#version: '3'
#services:
#  commerce:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env

version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  commerce:
    image: zin354/commerce:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env